### ISSUE TITLE
Error build-rust

### ISSUE THREAD

**Issue by coin77** [KZen-networks/thresh-sig-js#4]
Updating want v0.0.6 -> v0.2.0
    Updating zk-paillier v0.1.0 (https://github.com/KZen-networks/zk-paillier#fc10183a) -> #5688244b
'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @kzen-networks/thresh-sig@0.2.3 build-rust: `cd ./native && cargo update && cd .. && ./node_modules/.bin/neon build -r`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @kzen-networks/thresh-sig@0.2.3 build-rust script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nico\AppData\Roaming\npm-cache\_logs\2019-07-17T10_54_36_122Z-debug.log
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\nico\package.json'
npm WARN rollup-plugin-visualizer@1.1.1 requires a peer of rollup@>=0.60.0 but none is installed. You must install peer dependencies yourself.
npm WARN nico No description
npm WARN nico No repository field.
npm WARN nico No README data
npm WARN nico No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @kzen-networks/thresh-sig@0.2.3 postinstall: `npm run build-rust`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @kzen-networks/thresh-sig@0.2.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nico\AppData\Roaming\npm-cache\_logs\2019-07-17T10_54_36_440Z-debug.log
[2019-07-17T10_54_36_122Z-debug.log](https://github.com/KZen-networks/thresh-sig-js/files/3401509/2019-07-17T10_54_36_122Z-debug.log)

Please find the log attached.

Thank you.

**Comment by oleiba** [comment]
Hey, can tou please specify platform (Windows/MacOS), and Node version?
It seems that '.' is not recognized as a command, maybe problematic with your OS.
Maybe you can clone and modify the paths in `build-rust` script?

**Comment by coin77** [comment]
Windows 10, node v8.11.2.

**Comment by coin77** [comment]
Windows 10, node v8.11.2.

**Comment by oleiba** [comment]
I changed the `build-rust` script. It is now simply `neon build -r`, where `neon-cli` is a dependency.

**Comment by coin77** [comment]
```
error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
   --> C:\Users\nico\.cargo\registry\src\github.com-1ecc6299db9ec823\zeroize-0.10.1\src\lib.rs:201:1
    |
201 | extern crate alloc;
    | ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `zeroize`.
warning: build failed, waiting for other jobs to finish...
error: build failed
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (C:\Users\nico\node_modules\neon-cli\lib\target.js:121:35)
    at step (C:\Users\nico\node_modules\neon-cli\lib\target.js:32:23)
    at Object.next (C:\Users\nico\node_modules\neon-cli\lib\target.js:13:53)
    at fulfilled (C:\Users\nico\node_modules\neon-cli\lib\target.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

npm version: 6.10.1
OS: Windows 10

**Comment by oleiba** [comment]
which `rustc --version` are you using?
Try rustc 1.39.0-nightly
Node >= 10.16
npm >= 6.9

**Comment by doheto** [comment]
hello i have similar problem

i use : 
rustc 1.39.0-nightly
Node = 10.16.3
npm = 6.9.0

and i have this :

ld: library not found for -lgmp
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: aborting due to previous error

error: Could not compile `multi-party-eddsa`.
warning: build failed, waiting for other jobs to finish...
error: build failed
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/Users/GildasOswald/SMC/thresh-sig-js/node_modules/neon-cli/lib/target.js:121:35)
    at step (/Users/GildasOswald/SMC/thresh-sig-js/node_modules/neon-cli/lib/target.js:32:23)
    at Object.next (/Users/GildasOswald/SMC/thresh-sig-js/node_modules/neon-cli/lib/target.js:13:53)
    at fulfilled (/Users/GildasOswald/SMC/thresh-sig-js/node_modules/neon-cli/lib/target.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @kzen-networks/thresh-sig@0.3.4 build-rust: `neon build -r`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @kzen-networks/thresh-sig@0.3.4 build-rust script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/GildasOswald/.npm/_logs/2019-10-08T14_25_20_290Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @kzen-networks/thresh-sig@0.3.4 postinstall: `npm run build-rust`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @kzen-networks/thresh-sig@0.3.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.




Any idea ?

**Comment by oleiba** [comment]
Closing until further need.

**Comment by darklow** [comment]
I'm having similar rust build error as well related to same `paillier` lib.
```
   Compiling paillier v0.3.0 (https://github.com/KZen-networks/rust-paillier?tag=v0.3.0#735c95ec)
error[E0557]: feature has been removed
 --> /Users/darklow/.cargo/git/checkouts/rust-paillier-5e0399ff4bbd1793/735c95e/src/lib.rs:1:12
  |
1 | #![feature(custom_attribute)]
  |            ^^^^^^^^^^^^^^^^
  |
note: removed in favor of `#![register_tool]` and `#![register_attr]`
 --> /Users/darklow/.cargo/git/checkouts/rust-paillier-5e0399ff4bbd1793/735c95e/src/lib.rs:1:12
  |
1 | #![feature(custom_attribute)]
  |            ^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0557`.
error: could not compile `paillier`.
warning: build failed, waiting for other jobs to finish...
error: build failed
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/Users/darklow/www/contribute/thresh-sig-js/node_modules/neon-cli/lib/target.js:121:35)
    at step (/Users/darklow/www/contribute/thresh-sig-js/node_modules/neon-cli/lib/target.js:32:23)
    at Object.next (/Users/darklow/www/contribute/thresh-sig-js/node_modules/neon-cli/lib/target.js:13:53)
    at fulfilled (/Users/darklow/www/contribute/thresh-sig-js/node_modules/neon-cli/lib/target.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @kzen-networks/thresh-sig@0.3.5 build-rust: `neon build -r`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @kzen-networks/thresh-sig@0.3.5 build-rust script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/darklow/.npm/_logs/2019-11-21T10_33_40_989Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @kzen-networks/thresh-sig@0.3.5 postinstall: `npm run build-rust`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @kzen-networks/thresh-sig@0.3.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/darklow/.npm/_logs/2019-11-21T10_33_41_042Z-debug.log
```
```
rustc --version
rustc 1.41.0-nightly (5c5b8afd8 2019-11-16)
```
```
node -v
v9.6.1
```
```
npm -v
6.8.0
```

**Comment by darklow** [comment]
Upgraded to newest node and npm and now another error :(
```
node -v
v13.1.0

npm -v
6.12.1
```

```
error: failed to run custom build command for `neon-runtime v0.2.0`

Caused by:
  process didn't exit successfully: `/Users/darklow/www/contribute/thresh-sig-js/native/target/release/build/neon-runtime-ddc5a2c32449d04b/build-script-build` (exit code: 101)
--- stdout
Skipping node-gyp installation as part of npm install.
up to date in 2.94s

> @ build-release /Users/darklow/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.2.0
> node-gyp build

  CXX(target) Release/obj.target/neon/src/neon.o
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
AR_x86_64-apple-darwin = None
AR_x86_64_apple_darwin = None
HOST_AR = None
AR = None
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
running: "ar" "crs" "/Users/darklow/www/contribute/thresh-sig-js/native/target/release/build/neon-runtime-08b29894de5f0344/out/libneon.a" "build/Release/obj.target/neon/src/neon.o"
cargo:warning=ar: build/Release/obj.target/neon/src/neon.o: No such file or directory
exit code: 1

--- stderr
In file included from ../src/neon.cc:2:
In file included from ../node_modules/nan/nan.h:202:
In file included from ../node_modules/nan/nan_converters.h:67:
../node_modules/nan/nan_converters_43_inl.h:22:1: error: no viable conversion from 'Local<v8::Context>' to 'v8::Isolate *'
X(Boolean)
^~~~~~~~~~
../node_modules/nan/nan_converters_43_inl.h:18:23: note: expanded from macro 'X'
      val->To ## TYPE(isolate->GetCurrentContext())                            \
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:2639:37: note: passing argument to parameter 'isolate' here
  Local<Boolean> ToBoolean(Isolate* isolate) const;
                                    ^
In file included from ../src/neon.cc:2:
In file included from ../node_modules/nan/nan.h:202:
In file included from ../node_modules/nan/nan_converters.h:67:
../node_modules/nan/nan_converters_43_inl.h:40:1: error: no viable conversion from 'Local<v8::Context>' to 'v8::Isolate *'
X(bool, Boolean)
^~~~~~~~~~~~~~~~
../node_modules/nan/nan_converters_43_inl.h:37:29: note: expanded from macro 'X'
  return val->NAME ## Value(isolate->GetCurrentContext());                     \
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:2648:30: note: passing argument to parameter 'isolate' here
  bool BooleanValue(Isolate* isolate) const;
                             ^
In file included from ../src/neon.cc:2:
In file included from ../node_modules/nan/nan.h:203:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:103:42: error: no viable conversion from 'v8::Isolate *' to 'Local<v8::Context>'
  return scope.Escape(v8::Function::New( isolate
                                         ^~~~~~~
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:185:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::Isolate *' to 'const v8::Local<v8::Context> &' for 1st argument
class Local {
      ^
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:185:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::Isolate *' to 'v8::Local<v8::Context> &&' for 1st argument
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:189:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'v8::Isolate *'
  V8_INLINE Local(Local<S> that)
            ^
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:4189:22: note: passing argument to parameter 'context' here
      Local<Context> context, FunctionCallback callback,
                     ^
In file included from ../src/neon.cc:2:
In file included from ../node_modules/nan/nan.h:203:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:337:37: error: too few arguments to function call, expected 2, have 1
  return v8::StringObject::New(value).As<v8::StringObject>();
         ~~~~~~~~~~~~~~~~~~~~~      ^
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:5409:3: note: 'New' declared here
  static Local<Value> New(Isolate* isolate, Local<String> value);
  ^
In file included from ../src/neon.cc:2:
In file included from ../node_modules/nan/nan.h:203:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:337:58: error: expected '(' for function-style cast or type construction
  return v8::StringObject::New(value).As<v8::StringObject>();
                                         ~~~~~~~~~~~~~~~~^
../node_modules/nan/nan_implementation_12_inl.h:337:60: error: expected expression
  return v8::StringObject::New(value).As<v8::StringObject>();
                                                           ^
In file included from ../src/neon.cc:2:
../node_modules/nan/nan.h:1034:53: error: too few arguments to function call, single argument 'context' was not specified
      v8::Local<v8::String> string = from->ToString();
                                     ~~~~~~~~~~~~~~ ^
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:2627:3: note: 'ToString' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
  ^
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8config.h:368:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/neon.cc:2:
../node_modules/nan/nan.h:1044:37: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'char *'
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                                    ^~~~
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:2824:26: note: passing argument to parameter 'isolate' here
  int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
                         ^
In file included from ../src/neon.cc:2:
../node_modules/nan/nan.h:1818:28: error: no matching member function for call to 'Set'
    New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
    ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:3424:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:3427:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../src/neon.cc:2:
../node_modules/nan/nan.h:1824:28: error: no matching member function for call to 'Set'
    New(persistentHandle)->Set(key, value);
    ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:3424:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:3427:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../src/neon.cc:2:
../node_modules/nan/nan.h:1830:28: error: no matching member function for call to 'Set'
    New(persistentHandle)->Set(index, value);
    ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:3424:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:3427:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../src/neon.cc:2:
../node_modules/nan/nan.h:1836:32: error: no matching member function for call to 'Get'
        New(persistentHandle)->Get(New(key).ToLocalChecked()));
        ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:3471:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:3474:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/neon.cc:2:
../node_modules/nan/nan.h:1842:48: error: no matching member function for call to 'Get'
    return scope.Escape(New(persistentHandle)->Get(key));
                        ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:3471:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:3474:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/neon.cc:2:
../node_modules/nan/nan.h:1847:48: error: no matching member function for call to 'Get'
    return scope.Escape(New(persistentHandle)->Get(index));
                        ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:3471:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:3474:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/neon.cc:2:
In file included from ../node_modules/nan/nan.h:2657:
../node_modules/nan/nan_object_wrap.h:24:25: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(persistent().IsNearDeath());
           ~~~~~~~~~~~~ ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../src/neon.cc:2:
In file included from ../node_modules/nan/nan.h:2657:
../node_modules/nan/nan_object_wrap.h:67:18: error: no member named 'MarkIndependent' in 'Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    persistent().MarkIndependent();
    ~~~~~~~~~~~~ ^
../node_modules/nan/nan_object_wrap.h:124:26: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(wrap->handle_.IsNearDeath());
           ~~~~~~~~~~~~~ ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../src/neon.cc:8:
../src/neon_string.h:28:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    maybe.ToLocal(&result);
    ^~~~~~~~~~~~~ ~~~~~~~
In file included from ../src/neon.cc:10:
../src/neon_task.h:62:11: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    node::MakeCallback(isolate_, context->Global(), callback, 2, argv);
          ^
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/node.h:179:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/node.h:99:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
../src/neon.cc:163:26: error: too few arguments to function call, single argument 'isolate' was not specified
  return str->Utf8Length();
         ~~~~~~~~~~~~~~~ ^
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:2764:3: note: 'Utf8Length' declared here
  int Utf8Length(Isolate* isolate) const;
  ^
../src/neon.cc:341:56: error: too few arguments to function call, single argument 'context' was not specified
  v8::MaybeLocal<v8::Function> maybe = ft->GetFunction();
                                       ~~~~~~~~~~~~~~~ ^
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8.h:6004:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/darklow/Library/Caches/node-gyp/13.1.0/include/node/v8config.h:368:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.
make: *** [Release/obj.target/neon/src/neon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/Cellar/node/13.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /Users/darklow/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.2.0
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build-release: `node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/darklow/.npm/_logs/2019-11-21T10_52_22_014Z-debug.log
thread 'main' panicked at '

Internal error occurred: Command "ar" "crs" "/Users/darklow/www/contribute/thresh-sig-js/native/target/release/build/neon-runtime-08b29894de5f0344/out/libneon.a" "build/Release/obj.target/neon/src/neon.o" with args "ar" did not execute successfully (status code exit code: 1).

', /Users/darklow/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.55/src/lib.rs:1672:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/Users/darklow/www/contribute/thresh-sig-js/node_modules/neon-cli/lib/target.js:121:35)
    at step (/Users/darklow/www/contribute/thresh-sig-js/node_modules/neon-cli/lib/target.js:32:23)
    at Object.next (/Users/darklow/www/contribute/thresh-sig-js/node_modules/neon-cli/lib/target.js:13:53)
    at fulfilled (/Users/darklow/www/contribute/thresh-sig-js/node_modules/neon-cli/lib/target.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @kzen-networks/thresh-sig@0.3.5 build-rust: `neon build -r`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @kzen-networks/thresh-sig@0.3.5 build-rust script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/darklow/.npm/_logs/2019-11-21T10_52_51_190Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @kzen-networks/thresh-sig@0.3.5 postinstall: `npm run build-rust`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @kzen-networks/thresh-sig@0.3.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/darklow/.npm/_logs/2019-11-21T10_52_51_252Z-debug.log
```

**Comment by darklow** [comment]
If anyone encounters same errors on MacOS I was able to solve all the issues with following versions and fixes:
```
# node v10.17.0 (Fails with node 11+)
# npm 6.11.3
# rustc 1.39.0-nightly

# Setup older rustc (as it fails with newer 1.41+)
rustup install nightly-2019-08-27 --force
rustup override set nightly-2019-08-27

rustc --version
# rustc 1.39.0-nightly (9b91b9c10 2019-08-26)

brew install gmp
```

**Comment by oleiba** [comment]
@darklow Thank you so much for detailing that, glad it worked out eventually.
I'll take 2 action items here:
- detail in README what exact Rust version you need.
- open an issue for Paillier
